// Generated by CoffeeScript 1.3.0
(function() {
  var app, express, less, port, publicDir, routes;

  express = require('express');

  routes = require('./routes');

  publicDir = __dirname + '/public';

  app = module.exports = express.createServer();

  less = null;

  /*
  Configuration
  */


  express.compiler.compilers.less.compile = function(str, fn) {
    if (!less) {
      less = require("less");
    }
    try {
      return less.render(str, {
        compress: true
      }, fn);
    } catch (err) {
      return fn(err);
    }
  };

  app.configure(function() {
    app.set('views', __dirname + '/views');
    app.set('view engine', 'jade');
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(express.cookieParser());
    app.use(express.compiler({
      src: publicDir,
      enable: ['less']
    }));
    app.use(express["static"](publicDir));
    return app.use(app.router);
  });

  app.configure('development', function() {
    return app.use(express.errorHandler({
      dumpExceptions: true,
      showStack: true
    }));
  });

  app.configure('production', function() {
    return app.use(express.errorHandler());
  });

  app.get('/', function(req, res) {
    return res.render('index', {
      title: "Index"
    });
  });

  app.get('/cv', function(req, res) {
    return res.render('index', {
      title: "Cv coming soon"
    });
  });

  app.get('/contact', function(req, res) {
    return res.render('index', {
      title: "Contact page coming soon"
    });
  });

  app.get('/posts/new', function(req, res) {
    return res.render('index', {
      title: "you should not be here"
    });
  });

  port = process.env.PORT || 3000;

  app.listen(port, function() {
    return console.log("Express server listening on port %d in %s mode", app.address().port, app.settings.env);
  });

}).call(this);
